{
 "title": "Pokt Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": { "query": "label_values(region)" } },
   { "name": "chain_name", "label": "Blockchain", "query": { "query": "label_values(chain_name)" } },
   { "name": "mesh_moniker", "label": "Lean Node", "query": { "query": "label_values(moniker)" } }
  ]
 },
 "panels": [
  { "title": "GeoMesh Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Relay Rate By Region",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(region) (rate(pocketcore_geo_mesh_relay_count{region=~\"$region\", is_notify=\"false\", moniker=~\"$mesh_moniker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay Rate By Region/Chain",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(chain_name, region) (rate(pocketcore_geo_mesh_relay_count{chain_name=~\"$chain_name\", region=~\"$region\", is_notify=\"false\", moniker=~\"$mesh_moniker\"}[$__rate_interval]))",
     "legendFormat": "{{region}}:{{chain_name}}"
    }
   ]
  },
  {
   "title": "Relay Breakdown By Region",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region) (increase((pocketcore_geo_mesh_relay_count{chain_name=~\"$chain_name\", region=~\"$region\", is_notify=\"false\", moniker=~\"$mesh_moniker\"}[$__rate_interval])))",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Relay Breakdown by Region/Chain",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region, chain_name) (increase((pocketcore_geo_mesh_relay_count{chain_name=~\"$chain_name\", region=~\"$region\", is_notify=\"false\", moniker=~\"$mesh_moniker\"}[$__rate_interval])))",
     "legendFormat": "{{region}}:{{chain_name}}"
    }
   ]
  },
  {
   "title": "Relay Notifier Rate By Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (region) (rate(pocketcore_geo_mesh_tasks_completed_total{region=~\"$region\", stat_type=\"node\", moniker=~\"$mesh_moniker\"}[$__rate_interval]))",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Relay 6h Delta By Region",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(region) (delta(pocketcore_geo_mesh_relay_count{region=~\"$region\", is_notify=\"false\", moniker=~\"$mesh_moniker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay 6h Delta By Region/Chain",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by(chain_name, region) (delta(pocketcore_geo_mesh_relay_count{chain_name=~\"$chain_name\", region=~\"$region\", is_notify=\"false\", moniker=~\"$mesh_moniker\"}[6h]))",
     "legendFormat": "{{region}}:{{chain_name}}"
    }
   ]
  },
  {
   "title": "Latency By Region",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by(region) (rate(pocketcore_geo_mesh_relay_time_sum{chain_name=~\"$chain_name\", region=~\"$region\", is_notify=\"false\", moniker=~\"$mesh_moniker\"}[$__rate_interval])) / sum by(region) (rate(pocketcore_geo_mesh_relay_time_count{chain_name=~\"$chain_name\", region=~\"$region\", is_notify=\"false\", moniker=~\"$mesh_moniker\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency by Region/Chain",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum by(region, chain_name) (rate(pocketcore_geo_mesh_relay_time_sum{chain_name=~\"$chain_name\", region=~\"$region\", is_notify=\"false\", moniker=~\"$mesh_moniker\"}[$__rate_interval])) / sum by(region, chain_name) (rate(pocketcore_geo_mesh_relay_time_count{chain_name=~\"$chain_name\", region=~\"$region\", is_notify=\"false\", moniker=~\"$mesh_moniker\"}[$__rate_interval]))",
     "legendFormat": "{{region}}:{{chain_name}}"
    }
   ]
  },
  {
   "title": "Error Rate By Region",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by(region, status_code, status_type) (rate(pocketcore_geo_mesh_error_count{chain_name=~\"$chain_name\", region=~\"$region\", is_notify=\"false\", moniker=~\"$mesh_moniker\"}[$__rate_interval]))",
     "legendFormat": "{{region}}:{{status_type}}:{{status_code}}"
    }
   ]
  },
  {
   "title": "Error Rate By Region/Chain",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum by(chain_name, region, status_code, status_type) (rate(pocketcore_geo_mesh_error_count{chain_name=~\"$chain_name\", region=~\"$region\", is_notify=\"false\", moniker=~\"$mesh_moniker\"}[$__rate_interval]))",
     "legendFormat": "{{region}}:{{chain_name}}:{{status_type}}:{{status_code}}"
    }
   ]
  },
  {
   "title": "Moniker Worker Utilization %",
   "type": "timeseries",
   "description": "This is the servicer queue utilization per full node.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "(pocketcore_geo_mesh_tasks_waiting_total{moniker=~\"$mesh_moniker\"} / on(stat_type, node_name, moniker, region) pocketcore_geo_mesh_max_capacity{moniker=~\"$mesh_moniker\"}) * 100",
     "legendFormat": "{{region}}:{{moniker}}:{{stat_type}}"
    }
   ]
  },
  {
   "title": "Metric Worker Table",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "pocketcore_geo_mesh_max_workers{moniker=~\"$mesh_moniker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pocketcore_geo_mesh_min_workers{moniker=~\"$mesh_moniker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pocketcore_geo_mesh_max_capacity{moniker=~\"$mesh_moniker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pocketcore_geo_mesh_tasks_waiting_total{moniker=~\"$mesh_moniker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pocketcore_geo_mesh_tasks_failed_total{moniker=~\"$mesh_moniker\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}