[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"