// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Token struct {
	_tab flatbuffers.Table
}

func GetRootAsToken(buf []byte, offset flatbuffers.UOffsetT) *Token {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Token{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Token) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Token) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Token) Expdate(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Token) ExpdateLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Token) ExpdateBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TokenStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TokenAddExpdate(builder *flatbuffers.Builder, expdate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(expdate), 0)
}
func TokenStartExpdateVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TokenEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
