// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package messages

type Type = int32
const (
	TypeUNDEFINED Type = 0
	TypeDISC_HELLO Type = 1
)

var EnumNamesType = map[Type]string{
	TypeUNDEFINED:"UNDEFINED",
	TypeDISC_HELLO:"DISC_HELLO",
}

