// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ValidateMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsValidateMessage(buf []byte, offset flatbuffers.UOffsetT) *ValidateMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ValidateMessage{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ValidateMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ValidateMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ValidateMessage) Hash(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ValidateMessage) HashLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ValidateMessage) HashBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ValidateMessage) Relay(obj *Relay) *Relay {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Relay)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ValidateMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ValidateMessageAddHash(builder *flatbuffers.Builder, hash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(hash), 0)
}
func ValidateMessageStartHashVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ValidateMessageAddRelay(builder *flatbuffers.Builder, relay flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(relay), 0)
}
func ValidateMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
