version: '3'

services:

  pocket-core-service:
    image: poktnetwork/pocket-core:mvp-staging-latest
    build: ./.. 
    command:  --datadirectory ${POCKET_PATH_DATADIR:-datadir} --disip ${POCKET_CORE_DISPATCH_IP:-dispatch.pokt.network} --gid ${POCKET_CORE_SERVICE_GID:-xxx} --ip ${POCKET_CORE_SERVICE_IP:-localhost} --disrport ${POCKET_CORE_DISPATCH_PORT:-443} --port ${POCKET_CORE_SERVICE_PORT:-8081} --requestTimeout ${POCKET_CORE_REQUEST_TIMEOUT:-0} 
    ports:
      - "8081:8081"
    networks:
      - pocket
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      POCKET_CORE_DISPATCH_IP: "dispatch.pokt.network"
      POCKET_CORE_DISPATCH_PORT: 443
      POCKET_CORE_SERVICE_IP: "localhost"
      POCKET_CORE_SERVICE_PORT: 8081
      POCKET_PATH_DATADIR: "datadir"
      POCKET_CORE_SERVICE_GID: "xxx"
      POCKET_CORE_REQUEST_TIMEOUT: 0
      POCKET_CORE_START_DELAY: 5 
      POCKET_CORE_S3_CONFIG_URL: "s3://mybucket/service" # we expect a file 'chains.json' inside this dir 

networks:
  pocket:
    driver: bridge
