package _const

var(
	REPORTFILENAME = DATADIR+FILESEPARATOR+"reports.json"
	WHITELISTFILENAME = DATADIR+FILESEPARATOR+"whitelist.json"
	PEERFILENAME = DATADIR+FILESEPARATOR+"peers.json"
	CHAINSFILENAME = DATADIR+FILESEPARATOR+"chains.json"
)
